Rotate keys lambda logic
ciscops/colabot pull request #69
Opened 2022-07-06 17:44 UTC by ppajersk

2022-07-06 17:45 UTC, ppajersk commented
This code will be ready for review after it's completed and rebased with pr #68

2022-07-08 18:29 UTC, ppajersk commented
Code completed but not tested. Need to confirm a few additional cases and test all possible cases

2022-08-15 16:49 UTC, jlothian requested changes

2022-08-15 16:49 UTC, jlothian commented on awslambda/KeyManager.py
> +        self.logging.debug("Current key is 80 days old, creating new access key")
should the 80 here be a variable?

2022-08-15 16:49 UTC, jlothian commented on awslambda/KeyManager.py
> +            self.logging.debug("Key is 90 days old or older, deleting key")
variable for days

2022-08-15 16:49 UTC, jlothian commented on awslambda/KeyManager.py
> +            self.logging.debug("Key has not been used in 45 days, deleting key")
variable for days

2022-08-15 16:49 UTC, jlothian commented on awslambda/KeyManager.py
> +                "Key age is between 80-90 days old, warning user of expiration"
variable for days

2022-08-15 16:49 UTC, jlothian commented on awslambda/KeyManager.py
> +                "Key has not been used in 40-45 days, warning user of expiration"
variable for days

2022-08-15 20:13 UTC, jlothian approved these changes

2022-09-06 21:16 UTC, merged